### ISSUE TITLE
The animation restart when scroll

### ISSUE THREAD

**Issue by jeansevilla** [LottieFiles/lottie-interactivity#1]
Hi i am a visual designer, I have a problem with the code, I just want to play the animation and then loop by frame 50 to 250 frame. You can give me an examples for the solution? because I am not a coder. thank you

```
LottieInteractivity.create({
  player: '#maps',
  mode: 'scroll',
  actions: [
    {
      visibility: [0, 1],
      type: 'loop',
      frames: [[0,250],[50,250]],
    },
  ],
});
```

**Comment by karamalie** [comment]
Hey @jeansevilla . Thanks for bringing this up. will fix this bug on the interactivity library. Meanwhile If you re looking to just loop from 50 to 250  you can replace the entire code block with the code block below.

```

document
  .getElementById("maps")
  .getLottie()
  .playSegments([50, 250], true);

```

**Comment by jeansevilla** [comment]
> Hey @jeansevilla . Thanks for bringing this up. will fix this bug on the interactivity library. Meanwhile If you re looking to just loop from 50 to 250 you can replace the entire code block with the code block below.
> 
> ```
> 
> document.addEventListener("DOMContentLoaded", function({
> document.getElementById('maps').getLottie().playSegments([50,250]);
> }); 
> ```

I have tried to replace the entire block, but the animation just disappear... You know why? thank you

**Comment by karamalie** [comment]
Updated my answer. Give it a try with the new code block and let me know

**Comment by jeansevilla** [comment]
> Updated my answer. Give it a try with the new code block and let me know

Okey, now it works, but now the problem is that the animation starts when the page is loaded and not when you view the element, so the initial animation is lost. Do you know why? thank you 👍

**Comment by karamalie** [comment]
Try this @jeansevilla .  Frame 0 to 50 will sync with the scroll initially. when 30% of the Lottie is visible. (0.3 in the visibility) . and then it will loop from 50 to 250.

```
LottieInteractivity.create({
  player: '#maps',
  mode: 'scroll',
  actions: [
    {
      visibility: [0, 0.3],
      type: 'seek',
      frames: [0,50],
    },
    {
      visibility: [0.3, 1],
      type: 'loop',
      frames: [50,250],
    },
  ],
});
```

**Comment by jeansevilla** [comment]
> Try this @jeansevilla . Frame 0 to 50 will sync with the scroll initially. when 30% of the Lottie is visible. (0.3 in the visibility) . and then it will loop from 50 to 250.
> 
> ```
> LottieInteractivity.create({
>   player: '#maps',
>   mode: 'scroll',
>   actions: [
>     {
>       visibility: [0, 0.3],
>       type: 'seek',
>       frames: [0,50],
>     },
>     {
>       visibility: [0.3, 1],
>       type: 'loop',
>       frames: [50,250],
>     },
>   ],
> });
> ```

Hi, it doesn't work every time I scroll the animation restarts, I put the video here, also there is another problem the animation trembles. 

[problem.zip](https://github.com/LottieFiles/lottie-interactivity/files/4552478/problem.zip)

**Comment by MatiMenich** [comment]
Hi! I'm having the same problem, is there any news about this? Thanks!

**Comment by MatiMenich** [comment]
I've forked the repo and appears to be fixed on the latest commit, but it seems this fix is not reflected on the npm package.

**Comment by karamalie** [comment]
Fix has been implemented in newer versions.
