### ISSUE TITLE
Actions type: play loops the animation when lottie player loop prop = false

### ISSUE THREAD

**Issue by chriskightley92** [LottieFiles/lottie-interactivity#17]
So using the below code as an example, you can see that the action type is set to play. When the container comes into view, i'd just like the animation to play once and then end.

```
LottieInteractivity.create({
                mode: "scroll",
                player: "#get-involved-fireworks",
                container: "#get-involved-fireworks",
                actions: [
                    {
                        visibility: [0,1],
                        type: "play",
                    },
                ]
            });

<lottie-player id="get-involved-fireworks" src="https://assets9.lottiefiles.com/packages/lf20_yYFiWV.json"  background="transparent"  speed="1"></lottie-player>
```

However once the container comes into view, it just loops instead. Apologies if i've not set this up correctly as per documentation, but just needed to make sure this wasn't in fact an issue. 

Thanks

**Comment by jambelly22** [comment]
I have the same issue. Would be great if the animation could stop/pause at its last frame as I'm using multiple lottie animations on the page and I don't want them all running at once.
