### ISSUE TITLE
Uncaught ReferenceError: LottieInteractivity is not defined 

### ISSUE THREAD

**Issue by mingeunoh6** [LottieFiles/lottie-interactivity#3]
Hello!
I am trying to follow the instruction to control lottie json animation with mouse x-position, 
I set up the lottie player with script in the head
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>

and place lottie-player element in the HTML DOM, that worked smoothly. Animation showed up. And I installed lottie interactivity via npm and tried to follow the example code this github,

An Error showed up. 
**Uncaught ReferenceError: LottieInteractivity is not defined**

Do i have problem with install stage? 
**my npm messege was like this.**

> core-js@3.6.5 postinstall C:\Users\USER\Documents\practice_web\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\USER\Documents\practice_web\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\USER\Documents\practice_web\package.json'
npm WARN practice_web No description
npm WARN practice_web No repository field.
npm WARN practice_web No README data
npm WARN practice_web No license field.

+ @lottiefiles/lottie-interactivity@0.1.3
added 2 packages from 2 contributors and audited 2 packages in 3.997s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by mingeunoh6** [comment]
I think the problem was the location of my index.html. After revise the head script link directory that error dosent showed up but another error is occur.

**DevTools failed to load SourceMap: Could not load content for https://unpkg.com/lottie-player.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE**

**Comment by wlex-club** [comment]
the same problem

**Comment by karamalie** [comment]
could you post some snippets of your code @vle326 and also is this the error you are running into. just to confirm

DevTools failed to load SourceMap: Could not load content for https://unpkg.com/lottie-player.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by wlex-club** [comment]
ok I use this in vue template @karamalie
```
<template>
  <div id="app">
    <lottie-player
      autoplay
      controls
      loop
      mode="normal"
      src="https://assets3.lottiefiles.com/packages/lf20_UJNc2t.json"
      style="width: 320px"
    >
    </lottie-player>
  </div>
</template>

<script>
import '@lottiefiles/lottie-player'
import LottieInteractivity from '@lottiefiles/lottie-interactivity'

export default {
  name: 'app',
  created () {
    LottieInteractivity.create({
      mode: 'scroll',
      player: '#firstLottie',
      actions: [
        {
          visibility: [0, 1],
          type: 'seek',
          frames: [0, 100]
        }
      ]
    })
  }
}
</script>

```

so in the console some error like this:

[Vue warn]: Error in created hook: "TypeError: _lottiefiles_lottie_interactivity__WEBPACK_IMPORTED_MODULE_1__.default.create is not a function"

**Comment by karamalie** [comment]
```
<template>
  <div id="app">
    <lottie-player
      id="firstLottie"  // add an id to the element
      ref="myRef"     // add a ref to the element
      mode="normal"
      src="https://assets3.lottiefiles.com/packages/lf20_UJNc2t.json"
      style="width: 320px"
    >
    </lottie-player>
  </div>
</template>

<script>
import "@lottiefiles/lottie-player";
import { create } from "@lottiefiles/lottie-interactivity";

export default {
  name: "app",
  mounted () {
    this.$refs.myRef.addEventListener("load", function() {
      create({
        mode: "scroll",
        player: "#firstLottie",
        actions: [
          {
            visibility: [0, 1],
            type: "seek",
            frames: [0, 100],
          },
        ],
      });
    });
  }
}
</script>
```

Try referring to the above code @vle326 . In libraries such as vuejs and reactjs import the library as follows
`import { create } from '@lottiefiles/lottie-interactivity' `
will update the documentation with some examples

Move the method to be inside of the mounted lifecycle method rather than the created method. Moreover in react/vue the component renders before the Lottie itself renders. So you could listen for the animation load event before calling the interactivity library. 

You may also remove the following props from the Lottie element
` autoplay
   controls
   loop`

**Comment by wlex-club** [comment]
Got it , I will have a try, and i have another question -- how to run local data json , not by url
for example:
```
<div id="app">
    <lottie-player
      src="../data.json" // local data
    >
    </lottie-player>
```
@karamalie  Thanks a lot

**Comment by karamalie** [comment]
@vle326  for vuejs. place the json file in the root of the public folder and you should be able to link it like this

public folder structure 
- public
   - data.json
```
<div id="app">
    <lottie-player
      src="/data.json" 
    >
    </lottie-player>
```

construct it as a url if you are using a url. 

the other way is to read the json file as json string and then pass the json string to src. or parse the json file as a json object and then pass it to src. moving to the public folder is the simpler way
