### ISSUE TITLE
type=seek doesn't go back to the beginning of the animation

### ISSUE THREAD

**Issue by tentree-development** [LottieFiles/lottie-interactivity#36]
## Overview

I am trying to set up the type=seek and I can't get the animation go back to the beginning of the animation when you scroll up to the beginning of the page. If you go to [this page](https://lottiefiles.com/interactivity?url=https%3A%2F%2Fassets3.lottiefiles.com%2Fprivate_files%2Flf30_2c7wnifx.json) the animation doesn't go back to the beginning as you scroll up to the top of the page. Is this known bug? If there is the version working properly please let me know.

## Consuming repo

> What repo were you working in when this issue occurred?

I am working on the latest lottie-player and the latest lottie-interactivity.min.js

## Labels

- [ ] Add the `Type: Bug` label to this issue
![initial state](https://user-images.githubusercontent.com/73499009/134999923-f9c5e29f-5993-4d9f-b6b0-870569c8ecf2.png)
![after scroll up](https://user-images.githubusercontent.com/73499009/134999931-55277424-b1ed-4647-88f9-c49139c43455.png)
.

**Comment by samuelOsborne** [comment]
Hi @shinyatentree, the animation in that part of the page won't go to frame 0 because 70% of it is still visible even though you're at the top of the page and can't scroll any higher. If you go down the page a bit and find the 'sync lottie with scroll' section, you can see that as you scroll up and just a little bit of the animation is left (only the head peeking through) the animation will be at the start

https://user-images.githubusercontent.com/23125742/135060246-2e3e2baf-4d0f-4f60-a298-62e79d8822ae.mov

**Comment by tentree-development** [comment]
This implementation is not really suit for the full page Lottie animation like the following:
https://lottiefiles.com/interactivity?url=https%3A%2F%2Fassets7.lottiefiles.com%2Fprivate_files%2Flf30_xjt8yn4d.json

Can you take a look some implementation on another lottie javascript plugin like scrolll magic? https://codepen.io/jama1017/pen/ROymbz

**Comment by samuelOsborne** [comment]
@shinyatentree I think I see now what you're asking for. Currently the library doesn't have the ability to pin an animation so that we can scroll and keep the animation visible like the robot example you shared, but this would be interesting to add in the future!

**Comment by samuelOsborne** [comment]
@shinyatentree In the meantime, I think this was what you were looking for with your coffee animation:

https://codepen.io/Osbro/pen/JjJxymX

**Comment by tentree-development** [comment]
Thanks!
