### ISSUE TITLE
this.player.addEventListener is not a function error

### ISSUE THREAD

**Issue by paperbeatsscissors** [LottieFiles/lottie-interactivity#46]
## Overview

I have the Lottie library working on my site, but when I try to incorporate Lottie Interactivity I get the above error.

I'm loading the library via CDN:
```
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<script src="https://unpkg.com/@lottiefiles/lottie-interactivity@latest/dist/lottie-interactivity.min.js"></script>
```

and here's the instance:

```
<script>
    LottieInteractivity.create({
      mode: 'scroll',
      player: '#insight',
      actions: [{
        visibility: [0, 1.0],
        type: 'play'
      }]
    });
</script>
<lottie-player id="insight" src="/anim.json" style="width: 100%; height: auto;"></lottie-player>
```

Any idea what might be causing this?

...

## Consuming repo

> N/A

...

## Labels

- [x] Add the `Type: Bug` label to this issue.

**Comment by samuelOsborne** [comment]
Hi @paperbeatsscissors. This error usually occurs when you use a player id that can't be found in the DOM. Have you given your lottie-player an id of "insight" ?

**Comment by paperbeatsscissors** [comment]
@samuelOsborne yes, sorry, it was an error on my part! I think the function was executing before the library loaded - a DOM ready check solved it. Thank you!
