### ISSUE TITLE
`Type: Bug` Cursor mode not working on chrome mobile

### ISSUE THREAD

**Issue by Brodski** [LottieFiles/lottie-interactivity#49]
Hello,

On Chrome, if I try to sync the animation with the user's cursor then the animation won't play. Steps:

1. Choose a chrome browser on mobile, eg
   a) Chrome browser on Android Pixel
   b) Use the the google chrome desktop web browser and select the Responsive testing feature in chrome's web dev tools
2. Go to the hamster here https://lottiefiles.com/interactivity#ninth
3. Hold left click or using your finger to hold down then move cursor around.
4. The animation won't play :(

For https://github.com/LottieFiles/lottie-interactivity,

**Comment by Brodski** [comment]
Hi guys, I fixed this (in a way). I made it work for mouse movements on the X axis. I"m sure you can translate this to Y, or X+Y.
```
// implement a touch handler for mobile
// On touchmove event -> go to the frame based on % of cursor relative to lotties width
let lot = document.querySelector("#lottie-player-${UUID}")
let left = lot.getBoundingClientRect().left
let right = lot.getBoundingClientRect().right
let width = lot.getBoundingClientRect().width
let frames = lot.getLottie().totalFrames

lot.addEventListener("touchmove", (e)=> {
    if ( e.touches[0].clientX <= right && e.touches[0].clientX >=left) {
        let percentX = ((e.touches[0].clientX - left ) / width) * frames
        lot.getLottie().goToAndStop(percentX, true)
    }
})
```

**Comment by samuelOsborne** [comment]
Thanks for the ticket @Brodski , I'll look in to a fix for this.

**Comment by samuelOsborne** [comment]
Thanks for this @Brodski , I'll work on making more of the library's interactions work better for mobile in the future, cheers!
