### ISSUE TITLE
Cursor Position - on load, start position isn't start frame.

### ISSUE THREAD

**Issue by wplit** [LottieFiles/lottie-interactivity#5]
When I am syncing the animation with the cursor movement, say with the code below, shouldn't the animation be frozen at frame 20 until the cursor is over the animation?

`LottieInteractivity.create({
  player: '#firstLottie',
  mode: 'cursor',
  actions: [
    {
      position: { x: [0, 1], y: [0, 1] },
      type: 'seek',
      frames: [20, 100],
    },
  ],
});`

**Comment by karamalie** [comment]
You re right @wplit . looking into it.

In the meantime while i prep a new build, a quick hack would be to call the player.goToAndStop(frame,true) method and move the frame before the interactivity library is called but after the Lottie animation has loaded
