### ISSUE TITLE
Implement Horizontal Scrolling Support

### ISSUE THREAD

**Issue by nealwright** [LottieFiles/lottie-interactivity#50]
## Overview

It would be useful to implement horizontal scrolling support in addition to vertical scrolling support

...

## Type

- [X] New feature
- [ ] Changes to existing features

## Motivation

I'm working on a website which features a horizontal scrolling navigation with animations triggered by the horizontal scrolling. While libraries such as green socks support animation triggered by horizontal scrolling, it seems that Lottie Interactivity does not support this. I think implementing this feature would create a lot of opportunities for developers to use this library for horizontal-scrolling websites.

...

## Labels

- [ ] Add the `Type: Feature Request` label to this issue.

**Comment by samuelOsborne** [comment]
Thanks for the feature request @Hendeca ! 
This seems like an interesting feature and will add it to the roadmap. Thanks! :-)
