### ISSUE TITLE
Interactivity crashed after lottie-player destroy.

### ISSUE THREAD

**Issue by grogou** [LottieFiles/lottie-interactivity#63]
After lottie destroy I got this `this._cbs is null` error in console.

Is there a way to destroy interactivity with lottie, and after create new one?

**Comment by grogou** [comment]
This error happens when player mode is `chain` but when mode is `scroll` the error is `this.player.addEventListener is not a function`

**Comment by samuelOsborne** [comment]
@grogou You can call the stop() method after destroying your Lottie animation

**Comment by grogou** [comment]
Yes I do stop, after that destroy, the problem is same.

**Comment by grogou** [comment]
Can I help you implement path option on redefineOptions function to do it?

**Comment by samuelOsborne** [comment]
@grogou Looks like I don't remove scroll listener when calling stop(), my bad! 

I'll look in to implementing that yeah! Its a good addition, thanks.

**Comment by grogou** [comment]
If I can help you with implementation tell me. Thank you again))

**Comment by samuelOsborne** [comment]
@grogou Sorry I just looked at the code and refreshed, you can currently re-define a player with redefineOptions. 

It works the same was as the create method!

**Comment by grogou** [comment]
@samuelOsborne idk why but I still get same error.

On photo actions array for redefineOptions.

![image](https://user-images.githubusercontent.com/10712881/154667619-d9bb93c5-20a2-4dff-a9e1-2d34bfe9a49a.png)

**Comment by grogou** [comment]
@samuelOsborne I think the problem is https://github.com/LottieFiles/lottie-interactivity/blob/31ff4670b52dc7d3430edaa92a9270dcc100b393/src/main.js#L178 line where we save player, will we need to destroy old instance and create new one if path is defined in actions?

**Comment by grogou** [comment]
@samuelOsborne any change?

**Comment by samuelOsborne** [comment]
@grogou Looking in to it today.

**Comment by grogou** [comment]
@samuelOsborne thank you.

**Comment by samuelOsborne** [comment]
@grogou Can you try it out with v1.3.6? 

https://www.npmjs.com/package/@lottiefiles/lottie-interactivity/v/1.3.6

Let me know how it goes, cheers.

**Comment by grogou** [comment]
@samuelOsborne it works, but only for chain mode, when I do it with scroll mode browser get crashed under infinite loop.

**Comment by grogou** [comment]
Ah sorry loop is my fault. Under scroll mode it just didn't change lottie

**Comment by samuelOsborne** [comment]
@grogou Can you share what your code looks like please + the destroy and stopping parts

**Comment by grogou** [comment]
@samuelOsborne sure, but may I need to destroy player? It works without destroy under chain mode.

**Comment by samuelOsborne** [comment]
@grogou No you don't have to destroy, redefineOptions just changes the player and interactions you want with it. Destroying is up to you

**Comment by grogou** [comment]
`actions` array for redefineOptions

```
[
  {
    "visibility": [
      0,
      1
    ],
    "type": "seek",
    "frames": [
      0,
      286
    ],
    "path": "https://xpac.local/wp-content/uploads/2022/02/86577-meditating-monkeydd.json"
  }
]
```

**Comment by grogou** [comment]
> @grogou No you don't have to destroy, redefineOptions just changes the player and interactions you want with it. Destroying is up to you

Ye I did without stop or destroy

**Comment by samuelOsborne** [comment]
@grogou Ah I see the problem. Setting the path like that is only supported in chain mode. I think in your case you have to load a new lottie-player element, and call redefine options on the newly created player. And then destroy the old one

**Comment by grogou** [comment]
@samuelOsborne yes, anyway I need to clear old options for new lottie. Thank you again for your support. If you interested I can share with you that wordpress plugin when I will finish. So have a good day and cheers.

**Comment by samuelOsborne** [comment]
@grogou It would be great to get more info on what you're building, feel free to join the discord if you want to keep in touch:
https://lottiefiles.com/discord

Can also send my an email at: 
sam@lottiefiles.com

**Comment by grogou** [comment]
@samuelOsborne nice thanks, I will.
