### ISSUE TITLE
`this.container is undefined` after redefineOptions

### ISSUE THREAD

**Issue by grogou** [LottieFiles/lottie-interactivity#65]
After redefineOptions when interactivity destroy and recreate player, the `load` event listener callback called second time, all is good with player it works as expected, but we have an `this.container is undefined` error on console.

**Comment by samuelOsborne** [comment]
@grogou Looking in to this, in the mean time if you can share code that'd be great, cheers 🙌🏻

**Comment by grogou** [comment]
```js
if (url && interactivity === null) {   // The create part with listener
    lottie.current.addEventListener('load', () => {
        let createInteractivity = create({   // This part called 2 times
            player: `#${id}`,
            mode: mode,
            actions: actions,
        })
        setInteractivity(createInteractivity);
    });
}
if (interactivity !== null) {
    if (path === undefined) {
        setPath(url);
    }
    if (path !== url && path !== undefined) {
        actions[0].path = url;
        setPath(url);
    }
    interactivity.redefineOptions({
        player: `#${id}`,
        mode: mode,
        actions: actions,
    });
}
```

**Comment by samuelOsborne** [comment]
@grogou Do you want load to be called twice or is that a problem ? If its a problem you can do: 

```
lottie.current.addEventListener('load', () => {
        let createInteractivity = create({   // This part called 2 times
            player: `#${id}`,
            mode: mode,
            actions: actions,
        })
        setInteractivity(createInteractivity);
    }, {"once": true} );
```

**Comment by grogou** [comment]
@samuelOsborne it is the problem, yes I will try this, thank you, is it come frome my side? Just interesting case I guess. Anyway thank you.

**Comment by samuelOsborne** [comment]
@grogou Well since you're recreating the player a second time the event will be fired again. 

Im trying to understand the flow you have, is it like this:

> create player

> Wait for load event

> Create interactivity on the player

> Destroy player

> Load a new player

> Load event is fired again, recreating another interactivity instance and causing the container error

?

**Comment by grogou** [comment]
@samuelOsborne yes somthing like that. Your suggestion worked. I think after recreate the lottie ref got changed and when I try to remove that listener nothing happen. So the problem in my opinion is that wrong lottie ref. But your suggestion fix it. We can close this ticket I guess. Thank you very much again, you best))

**Comment by samuelOsborne** [comment]
@grogou 🙌🏻
