### ISSUE TITLE
Set Lottie Interactivity JS

### ISSUE THREAD

**Issue by iroshiva** [LottieFiles/lottie-interactivity#68]
Hi !

I tried setting lottie-interactivity as described on your site https://lottiefiles.com/interactivity

- npm install --save @lottiefiles/lottie-interactivity
- npm install --save @lottiefiles/lottie-player

In a file lottie.js

```
import "@lottiefiles/lottie-player";
import  { LottieInteractivity } from '@lottiefiles/lottie-interactivity';

LottieInteractivity.create({
    player:'#firstLottie',
    mode:"scroll",
        actions: [
        {
          visibility:[0, 1.0],
          type: "seek",
          frames: [0, 300],
        },
        ]
});
```

Got this error message: `"_lottiefiles_lottie_interactivity__WEBPACK_IMPORTED_MODULE_1__.LottieInteractivity.create is not a function"`

Search and did:
`import  { LottieInteractivity, create } from '@lottiefiles/lottie-interactivity';`

Had the same error....

Search again, and did:
```
window.addEventListener('load', function () { 
  create({
    player:'#firstLottie',
    mode:"scroll",
        actions: [
        {
          visibility:[0, 1.0],
          type: "seek",
          frames: [0, 300],
        },
        ]
    });
})
```

Finally works !!

My question is: why the code in the site didn't work at the beginning ??
My way to do is the right one ?

Thx

**Comment by samuelOsborne** [comment]
Hi @iroshiva, it's because we export the create method:

```
export const create = options => {
  const instance = new LottieInteractivity(options);
  instance.start();

  return instance;
};

export default create;
```

So thats why your first code doesn't work but when you import ```create``` it does.

Hopefully I anwsered your question, feel free to ask more if you have any.

Cheers

**Comment by iroshiva** [comment]
Aaallright !

Should maybe be part of the tutorial when using lottie interactivity from npm / yarn ?

Thx

**Comment by samuelOsborne** [comment]
@iroshiva Which tutorial would that be ? In our readme we have examples for React and Vue:
https://github.com/LottieFiles/lottie-interactivity#31-react-config

**Comment by iroshiva** [comment]
@samuelOsborne ,

That one, for people not using React or Yarn.

https://lottiefiles.com/interactivity

**Comment by samuelOsborne** [comment]
Ok thanks @iroshiva will pass it on!
