### ISSUE TITLE
Animate when visible does not loop 

### ISSUE THREAD

**Issue by k3lv1n90** [LottieFiles/lottie-interactivity#69]
## Overview

When using animate when visible, the lottie file plays only once and does not loop even if we used the loop data-attribute
This is an example taken from https://docs.lottiefiles.com/lottie-interactivity/animation-modes#animate-when-visible
https://codepen.io/mdavid1/pen/zYPGJzL
You'll need to add 'loop' somewhere in the <lottie-player> tag

## Consuming repo

> What repo were you working in when this issue occurred?
Lottie-Interactivity
...

## Labels

- [ ] Add the `Type: Bug` label to this issue.

**Comment by k3lv1n90** [comment]
I've resorted to adding an if condition so that it will loop when it is visible
```
  actions: [
    {
      visibility: [0.5, 1.0],
      type: "loop",
      frames: [0,61],
    }
```

else 

```
  actions: [
    {
      visibility: [0.5, 1.0],
      type: "play",
    }
```

**Comment by samuelOsborne** [comment]
Hi @k3lv1n90, the usual way to have it loop when visible is like this:

```
LottieInteractivity.create({
  player: "#twelfthLottie",
  mode: "scroll",
  actions: [
    {
      visibility: [0.5, 1.0],
      type: "loop",
      frames: [0, 61]
    }
  ]
});

```

so with mode: 'scroll' and type: 'loop' it'll loop when it becomes visible.

If you're solution works than thats great too, let me know if I can clear anything up for you! But if its all good then I'll close this issue :-)

cheers!

**Comment by k3lv1n90** [comment]
yeah I figured it out, just a bit weird that the player does not take into consideration the loop data-attribute
