### ISSUE TITLE
Animation jumping on iOS

### ISSUE THREAD

**Issue by davist11** [LottieFiles/lottie-interactivity#7]
```
"@lottiefiles/lottie-interactivity": "^0.1.3",
"@lottiefiles/lottie-player": "^0.5.1",
```

We are using using lottie scroll relative to a container, and I'm seeing an issue where the animation is jumping on iOS. The container is `400vh` and the `<lottie-player>` is `100vh`. I can throw a background color on the `<lottie-player>` and confirm it takes up the entire screen height.

![IMG_658B4D47A9A3-1](https://user-images.githubusercontent.com/199985/91873224-c4b0ac00-ec46-11ea-9397-bb85943fa245.jpeg)

But occasionally, the animation jumps to the top on iOS, and I can't determine any consistent reason why.

Here's a video of the bug: https://drive.google.com/file/d/1nWLhe_5m3qtA4vYyQ_ebAd9jcWVlD29g/view?usp=sharing

Let me know if there is any other information I can provide.

**Comment by karamalie** [comment]
Hi Trevor,

Would it be possible to pass us the Lottie file so we could test it.
Thank you

**Comment by davist11** [comment]
Hah that would have been helpful, sorry

https://assets5.lottiefiles.com/private_files/lf30_LCvZZF.json

**Comment by karamalie** [comment]
Could you have a look at this codesandbox 

https://8bz9z.csb.app/

The jump happens in safari because it does not support certain css transforms. To fix it, have a look at the css

```
  <style>
      .container {
        width: 100%;
        height: 100vh;
      }
      .content {
        width: 100%;
        height: 400vh;
      }
      #firstLottie {
        width: 400px;
        height: auto;
        position: fixed;
        top: 50%;
        right: 50%;
        transform: translate(50%, -50%);
        -webkit-transform: translate3d(50, 0, 0);
      }
    </style>
```



```
    <div style="height: 400px; background: red;"></div>
    <div style="height: 400vh;">
      <lottie-player
        id="firstLottie"
        src="https://assets5.lottiefiles.com/private_files/lf30_LCvZZF.json"
        background="transparent"
        speed="1"
      ></lottie-player>
      <div id="container" class="container">
        <div id="content" class="content"></div>
      </div>
    </div>
    <div style="height: 400px; background: red;"></div>
```



```
    <script>
      LottieInteractivity.create({
        mode: "scroll",
        player: "#firstLottie",
        container: "#content",
        actions: [
          {
            visibility: [0, 1],
            type: "seek",
            frames: [0, 1000]
          }
        ]
      });
    </script>

```

The  -webkit-transform: translate3d(50, 0, 0); is key
