### ISSUE TITLE
Issue on 'chain' mode with 'hold' and 'pauseHold' with 'onComplete' segments

### ISSUE THREAD

**Issue by EricBeaupere** [LottieFiles/lottie-interactivity#77]
## Overview

Hi,
I'm testing the "chain" mode with 5 segments, and I can't get "pause" and "pauseHold" to work.
It doesn't work with "onComplete" segments before the "pause" segment but work without "onComplete" segment before (see the second animation test below the first).
The Lottie files and the code is here :
https://www.studiobouton.fr/lottie-example/
thanks

## Consuming repo

> What repo were you working in when this issue occurred?
wordpress/html
...

## Labels

- [ ] Add the `Type: Bug` label to this issue.

**Comment by samuelOsborne** [comment]
Looking in to this @EricBeaupere

**Comment by EricBeaupere** [comment]
Sorry @samuelOsborne, but I don't see any link or answer in your comment ? 🤔 
thank you for your time spent

**Comment by samuelOsborne** [comment]
Hey @EricBeaupere I think I got it working as you want with this setup:

```
LottieInteractivity.create({
            player: '#...',
            mode: "chain",
            actions: [
                {
                    state: 'autoplay',
                    transition: 'onComplete',
                    frames: [0, 35],
                },
                {
                    state: 'hold',
                    transition: 'hold',
                    frames: [35, 130],
                },
                {
                    state: 'autoplay',
                    transition: 'onComplete',
                    frames: [130, 491],
                }, {
                    state: 'hold',
                    transition: 'pauseHold',
                    frames: [491, 612]
                },
                {
                    state: 'autoplay',
                    transition: 'none',
                    frames: [612, 1074],
                }
            ]
        });
```

Basically with the hold and pauseHold transitions doesn't control how the animation plays, that's why I added them to the 'state' and I believe it works as you intended.

It's a really cool animation, please do share wherever it  goes in to production ! :))

Edit:

Spoke too soon, the animation is autoplaying too far in the beginning..🤔  looking in to it

**Comment by EricBeaupere** [comment]
Thanks @samuelOsborne, 
indeed it's autoplaying with "hold" state.
I also test with "hover" state, It's work pretty fine for the first "hold" section.
But it don't work with "pausehold" 😞 
https://www.studiobouton.fr/lottie-example/
I tested a lot of things but I feel stuck right now.
Maybe it can't work with the lottie-interactivity library ?
thanks for the technical support.

**Comment by samuelOsborne** [comment]
@EricBeaupere Working on a bug fix to solve this! Will ping you when it's out, should be some time today

**Comment by samuelOsborne** [comment]
Hi @EricBeaupere could you please update to v1.5.1 (latest) and change your config to this:

```
  LottieInteractivity.create({
    player: '#...',
    mode: "chain",
    actions: [
      {
        state: 'autoplay',
        transition: 'onComplete',
        frames: [0, 35],
      },
      {
        state: 'hold',
        transition: 'hold',
        frames: [35, 130],
      },
      {
        state: 'autoplay',
        transition: 'onComplete',
        frames: [130, 491],
      }, {
        state: 'pauseHold',
        transition: 'pauseHold',
        frames: [491, 612]
      },
      {
        state: 'autoplay',
        transition: 'onComplete',
        frames: [612, 1074],
      },
      {
        state: 'none',
        transition: 'click',
        reset: true
      }
    ]
  });
```

**Comment by EricBeaupere** [comment]
So cooool ! It's works perfectly. 👌 
Thanks a lot, you have made my day. 🦸  I will tell you when this animation goes in to production. 
I see lot of fun potentials into  lottie interactivity. 🎆  I 'll continue to test and imagine animations about this.
I have a last question, is it possible to have a "cursor" interactivity into a "chain"; For example to replace the "pauseHold" into my animation, i don't see anything about this in the interactivity guide.
thanks.

**Comment by samuelOsborne** [comment]
Awesome @EricBeaupere Please do!

Could you explain more about what interaction you'd like the cursor to be ? For the moment there is only sync to cursor when in chain mode:

https://lottiefiles.com/interactivity#syncExample

**Comment by EricBeaupere** [comment]
Now I remember I tried this in an other animation.
I made the test for this one, below the first, but it don't work very well.
https://www.studiobouton.fr/lottie-example/
I imagine the slider pulling the crane.

**Comment by samuelOsborne** [comment]
@EricBeaupere I see, that would work well. Let me have a play around and see what I can do!

**Comment by EricBeaupere** [comment]
Hi @samuelOsborne , I finished the page on Lottie animations with several examples, including the one above with interactivity.
You can see it here (not a public page at the moment) :
https://www.studiobouton.fr/lottie/
On the other hand, when I scroll the page up and down without hovering over the animations, they sometimes start anyway.
each animation has a unique ID

**Comment by samuelOsborne** [comment]
Absolutely love this @EricBeaupere, please do ping me when it goes public, I can share with our marketing team if you'd like.

Regarding your issue, all your players on that page have the autoplay attribute, try removing it from the ones you don't want to start playing automatically

**Comment by EricBeaupere** [comment]
It's works fine now, thank you @samuelOsborne, and of course, you'll can share the link with the marketing team.
I'll keep you informed.

**Comment by EricBeaupere** [comment]
Hi @samuelOsborne , the page is now online 
https://www.studiobouton.fr/lottie/
Thank you for your technical support

**Comment by samuelOsborne** [comment]
hey @EricBeaupere could you send me an email at: 

sam@lottiefiles.com

I'd love to talk more about your process and get in touch with you, cheers!
