### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by stefanooni** [LottieFiles/lottie-interactivity#78]
## Overview
It would be great if we could get Typescript support with type declarations for each module.
...

## Type

- [x] New feature
- [ ] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing, or what else makes you think this should be
> included?
Let's support those who choose to use Typescript.
...

## Labels

- [ ] Add the `Type: Feature Request` label to this issue.

**Comment by samuelOsborne** [comment]
Hi @stefanooni Thanks for bringing this to our attention, will look in to it.
