### ISSUE TITLE
Path property is not working using react and lottie-react

### ISSUE THREAD

**Issue by drakyone** [LottieFiles/lottie-interactivity#85]
## Overview
Path property is not working using react and lottie-react + lottie-interactivity, here's an example 
https://codesandbox.io/s/busy-grass-fzxr45
Any suggestions will be highly appreciated, thanks!

**Comment by samuelOsborne** [comment]
Will look in to this and get back to you @drakyone. Seems like a problem with the library.

**Comment by shuheen** [comment]
Any update on this?

**Comment by samuelOsborne** [comment]
hi @shuheen haven't had time to work on this yet. If you or @drakyone would feel comfortable enough taking a crack at it feel free and I would happily review. Will keep you posted, the earliest I can start on this is the week after next.

Cheers

**Comment by drakyone** [comment]
@samuelOsborne hey, I fixed it but couldn't push branch because of the permissions, could you check this please
![Скриншот 22-06-2022 234247](https://user-images.githubusercontent.com/75342699/175132383-51751fd5-a6af-4437-bafa-c16dbdd8b8c9.jpg)
it's failed because stop method set null to player on the line above

![Скриншот 22-06-2022 234132](https://user-images.githubusercontent.com/75342699/175132425-d4984102-df1e-4801-a307-6b7ebaa39b87.jpg)

to make it work we need just to remove this.player.destroy() on the line number 745

**Comment by samuelOsborne** [comment]
@drakyone I've added this to v1.6.1. Thanks for your help!
