### ISSUE TITLE
Assign animation actions on button click.

### ISSUE THREAD

**Issue by dlogvin** [LottieFiles/lottie-interactivity#88]
## Overview

Whenever a user clicks a button, the animation of an object would change.

## Type

- New feature

## Motivation

> What inspired this feature request? What problems were you facing, or what else makes you think this should be
> included?

I'm just trying to trigger animations through buttons and not clicking on them directly.

**Comment by samuelOsborne** [comment]
Hi @dlogvin Thanks for submitting this, this is a good feature and will add it to the roadmap to implement.

Cheers
