### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by luc122c** [LottieFiles/lottie-interactivity#94]
## Overview

Hi There, I was just wondering if there were any plans for TypeScript support for this package on the horizon? 

## Type

- [ ] New feature
- [X] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing, or what else makes you think this should be
> included?

The [lottie-player package](https://github.com/LottieFiles/lottie-player) publishes types and it's extremely helpful when configuring a player in a TypeScript project. 

## Labels

- [X] Add the `Type: Feature Request` label to this issue.

**Comment by samuelOsborne** [comment]
Hi @luc122c there is, just currently it isn't the priority.
