### ISSUE TITLE
dotlottie support

### ISSUE THREAD

**Issue by alolalo** [LottieFiles/lottie-interactivity#95]
## Overview

...

## Type

Would like to be able to use the lottie-player webcomponent, and the dotlottie-player webcomponent with interactivity.

## Motivation

The players have identical naming due to the file-format, and is already incorporated as an export function.

https://github.com/dotlottie/player-component

...

## Labels

- [ ] Add the `Type: Feature Request` label to this issue.

**Comment by samuelOsborne** [comment]
Hi @alolalo , dotLottie support JSON and .lottie files, so do you think you still need the lottie-player component?

For interactivity with dotLottie check out this code:

https://codepen.io/Osbro/pen/VwXbwmV

**Comment by alolalo** [comment]
Fantastic stuff! I'm happy that it's so simple, so others can teach others. Thanks!
